apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spshk-production-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jaosullivan/spshk-platform'
    targetRevision: main
    path: k8s-gitops/environments/production
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spshk-local
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
